name: Release
on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: npm install
        run: |
          if [ ! -d "./node_modules" ]; then
              cp ./package.json ./package.backup.json
              cp ./package-lock.json ./package-lock.backup.json
              npm remove --save node-appletv
              npm ci
              mv -f ./package.backup.json ./package.json
              mv -f ./package-lock.backup.json ./package-lock.json
          fi
      - run: npm run check
  release:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: semantic-release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
